-- 1. CLEANUP: Dropping all tables in dependency order
DROP TABLE IF EXISTS draft CASCADE;
DROP TABLE IF EXISTS standings CASCADE;
DROP TABLE IF EXISTS plays CASCADE;
DROP TABLE IF EXISTS player_stats CASCADE;
DROP TABLE IF EXISTS schedule CASCADE;
DROP TABLE IF EXISTS rosters CASCADE;
DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS teams CASCADE;

-- 2. TEAMS: Literal mirror of teams.csv [cite: 5]
CREATE TABLE teams (
    id BIGINT PRIMARY KEY,
    seasonid BIGINT,
    abbrev TEXT,
    logo TEXT,
    darklogo TEXT,
    french TEXT,
    scrapedon TEXT,
    source TEXT,
    commonname_default TEXT,
    name_default TEXT,
    name_fr TEXT,
    placenamewithpreposition_default TEXT,
    placenamewithpreposition_fr TEXT,
    placename_default TEXT,
    placename_fr TEXT,
    commonname_fr TEXT,
    fullname TEXT,
    lastseason BIGINT,
    teamcommonname TEXT,
    teamplacename TEXT,
    firstseason_id BIGINT,
    lastseason_id BIGINT,
    firstseasonid BIGINT,
    lastseasonid BIGINT,
    mostrecentteamid BIGINT,
    teamabbrev TEXT,
    teams JSONB
);

-- 3. PLAYERS: Full bio support from roster.csv [cite: 4]
CREATE TABLE players (
    id BIGINT PRIMARY KEY,
    headshot TEXT,
    sweaternumber NUMERIC,
    positioncode TEXT,
    shootscatches TEXT,
    heightininches NUMERIC,
    weightinpounds NUMERIC,
    heightincentimeters NUMERIC,
    weightinkilograms NUMERIC,
    birthdate DATE,
    birthcountry TEXT,
    scrapedon TEXT,
    source TEXT,
    firstname_default TEXT,
    lastname_default TEXT,
    birthcity_default TEXT,
    birthstateprovince_default TEXT,
    birthcity_fi TEXT, birthcity_sv TEXT, birthcity_cs TEXT, birthcity_sk TEXT,
    firstname_cs TEXT, firstname_de TEXT, firstname_es TEXT, firstname_fi TEXT, 
    firstname_sk TEXT, firstname_sv TEXT, birthcity_fr TEXT,
    lastname_cs TEXT, lastname_fi TEXT, lastname_sk TEXT, lastname_sv TEXT,
    birthcity_de TEXT, lastname_de TEXT, lastname_es TEXT,
    season BIGINT, teamabbrev TEXT
);

-- 4. ROSTERS: Tracking seasonal player-team links [cite: 4, 7]
CREATE TABLE rosters (
    id BIGINT REFERENCES players(id),
    season BIGINT,
    teamabbrev TEXT,
    sweaternumber NUMERIC,
    positioncode TEXT,
    firstname_default TEXT,
    lastname_default TEXT,
    birthcity_sv TEXT, birthcity_fi TEXT, birthcity_cs TEXT, birthcity_sk TEXT, birthcity_fr TEXT,
    firstname_sv TEXT, firstname_de TEXT, firstname_sk TEXT, firstname_cs TEXT, firstname_es TEXT, firstname_fi TEXT,
    birthdate DATE, birthcountry TEXT, birthcity_default TEXT, birthstateprovince_default TEXT,
    headshot TEXT, weightinpounds NUMERIC, heightininches NUMERIC, heightincentimeters NUMERIC,
    weightinkilograms NUMERIC, shootscatches TEXT, scrapedon TEXT, source TEXT,
    PRIMARY KEY (id, season)
);

-- 5. SCHEDULE: Captures operational and logistical data [cite: 3, 7]
CREATE TABLE schedule (
    id BIGINT PRIMARY KEY,
    season BIGINT,
    gametype NUMERIC,
    gamedate DATE,
    neutralsite NUMERIC,
    starttimeutc TEXT,
    easternutcoffset TEXT,
    venueutcoffset TEXT,
    venuetimezone TEXT,
    gamestate TEXT,
    gameschedulestate TEXT,
    tvbroadcasts JSONB,
    threeminrecap TEXT,
    threeminrecapfr TEXT,
    condensedgame TEXT,
    condensedgamefr TEXT,
    gamecenterlink TEXT,
    scrapedon TEXT,
    source TEXT,
    venue_default TEXT,
    awayteam_id BIGINT,
    awayteam_commonname_default TEXT,
    awayteam_placename_default TEXT,
    awayteam_placenamewithpreposition_default TEXT,
    awayteam_placenamewithpreposition_fr TEXT,
    awayteam_abbrev TEXT,
    awayteam_logo TEXT,
    awayteam_darklogo TEXT,
    awayteam_awaysplitsquad NUMERIC,
    awayteam_score NUMERIC,
    hometeam_id BIGINT,
    hometeam_commonname_default TEXT,
    hometeam_placename_default TEXT,
    hometeam_placenamewithpreposition_default TEXT,
    hometeam_placenamewithpreposition_fr TEXT,
    hometeam_abbrev TEXT,
    hometeam_logo TEXT,
    hometeam_darklogo TEXT,
    hometeam_homesplitsquad NUMERIC,
    hometeam_score NUMERIC,
    perioddescriptor_periodtype TEXT,
    perioddescriptor_maxregulationperiods NUMERIC,
    gameoutcome_lastperiodtype TEXT,
    winninggoalie_playerid BIGINT,
    winninggoalie_firstinitial_default TEXT,
    winninggoalie_lastname_default TEXT,
    awayteam_placename_fr TEXT,
    winninggoalie_lastname_cs TEXT,
    winninggoalie_lastname_fi TEXT,
    winninggoalie_lastname_sk TEXT,
    winninggoalie_lastname_sv TEXT,
    winninggoalscorer_playerid BIGINT,
    winninggoalscorer_firstinitial_default TEXT,
    winninggoalscorer_lastname_default TEXT,
    venue_fr TEXT,
    hometeam_commonname_fr TEXT,
    awayteam_commonname_fr TEXT,
    hometeam_hotellink TEXT,
    hometeam_hoteldesc TEXT,
    awayteam_airlinelink TEXT,
    awayteam_airlinedesc TEXT,
    awayteam_hotellink TEXT,
    awayTeam_hoteldesc TEXT,
    hometeam_airlinelink TEXT,
    hometeam_airlinedesc TEXT,
    hometeam_placename_fr TEXT,
    ticketslink TEXT,
    ticketslinkfr TEXT,
    awayteam_radiolink TEXT,
    hometeam_radiolink TEXT,
    awayteam_promolink TEXT,
    awayteam_promodesc TEXT,
    hometeam_promolink TEXT,
    hometeam_promodesc TEXT,
    venue_es TEXT,
    seriesurl TEXT,
    seriesstatus_round NUMERIC,
    seriesstatus_seriesabbrev TEXT,
    seriesstatus_seriestitle TEXT,
    seriesstatus_seriesletter TEXT,
    seriesstatus_neededtowin NUMERIC,
    seriesstatus_topseedwins NUMERIC,
    seriesstatus_bottomseedwins NUMERIC,
    seriesstatus_gamenumberofseries NUMERIC,
    specialevent_parentid BIGINT,
    specialevent_name_default TEXT,
    specialevent_lightlogourl_default TEXT,
    venue_cs TEXT,
    venue_fi TEXT,
    venue_sk TEXT,
    alternatebroadcasts JSONB
);

-- 6. PLAYS: Full CSV mirror to game.csv [cite: 6, 7]
CREATE TABLE plays (
    id TEXT PRIMARY KEY,
    gameid BIGINT REFERENCES schedule(id),
    sortorder NUMERIC,
    per NUMERIC,
    strength TEXT,
    event TEXT,
    description TEXT,
    time TEXT,
    timeremaining TEXT,
    timeinperiodsec NUMERIC,
    timeremainingsec NUMERIC,
    home_on_ice JSONB,
    away_on_ice JSONB,
    home_goalie JSONB,
    away_goalie JSONB,
    merge_idx NUMERIC,
    eventid NUMERIC,
    timeinperiod TEXT,
    timeremaining_api TEXT,
    situationcode TEXT,
    hometeamdefendingside TEXT,
    typecode TEXT,
    event_api TEXT,
    period NUMERIC,
    periodtype TEXT,
    maxregulationperiods NUMERIC,
    teamid_ BIGINT,
    losingplayerid BIGINT,
    winningplayerid BIGINT,
    xcoord NUMERIC,
    ycoord NUMERIC,
    zonecode TEXT,
    hittingplayerid BIGINT,
    hitteeplayerid BIGINT,
    shottype TEXT,
    shootingplayerid BIGINT,
    goalieinnetid BIGINT,
    awaysog NUMERIC,
    homesog NUMERIC,
    playerid BIGINT,
    reason TEXT,
    blockingplayerid BIGINT,
    typecode_1 TEXT,
    desckey TEXT,
    duration NUMERIC,
    committedbyplayerid BIGINT,
    drawnbyplayerid BIGINT,
    secondaryreason TEXT,
    pptreplayurl TEXT,
    scoringplayerid BIGINT,
    scoringplayertotal NUMERIC,
    assist1playerid BIGINT,
    assist1playertotal NUMERIC,
    awayscore NUMERIC,
    homescore NUMERIC,
    highlightclipsharingurl TEXT,
    highlightclip TEXT,
    discreteclip TEXT,
    assist2playerid BIGINT,
    assist2playertotal NUMERIC,
    ishome BOOLEAN,
    eventteam TEXT,
    html_event TEXT,
    home_on_id JSONB,
    away_on_id JSONB,
    homegoalie_on_id JSONB,
    awaygoalie_on_id JSONB,
    home_on_full_name JSONB,
    away_on_full_name JSONB,
    homegoalie_on_full_name JSONB,
    awaygoalie_on_full_name JSONB,
    home_on_count NUMERIC,
    away_on_count NUMERIC,
    homegoalie_on_count NUMERIC,
    awaygoalie_on_count NUMERIC,
    n_home_skaters NUMERIC,
    n_away_skaters NUMERIC,
    pulled_home NUMERIC,
    pulled_away NUMERIC,
    home_strength TEXT,
    away_strength TEXT,
    gamestrength TEXT,
    detailedgamestrength TEXT,
    elapsedtime NUMERIC,
    player1id BIGINT,
    player2id BIGINT,
    player3id BIGINT,
    player1name TEXT,
    player2name TEXT,
    player3name TEXT,
    hometeam TEXT,
    awayteam TEXT,
    teamid BIGINT,
    isgoalie BOOLEAN,
    venue TEXT,
    venuelocation TEXT,
    gamedate DATE,
    gametype NUMERIC,
    starttimeutc TEXT,
    easternutcoffset TEXT,
    venueutcoffset TEXT,
    scrapedon TEXT,
    source TEXT,
    x_norm NUMERIC,
    y_norm NUMERIC,
    distancefromgoal NUMERIC,
    angle_signed NUMERIC,
    strengthdiff NUMERIC,
    scorediff NUMERIC,
    shooterskaters NUMERIC,
    defendingskaters NUMERIC,
    shootemptynet BOOLEAN,
    previousevent TEXT,
    previousteam TEXT,
    previouseventsameteam BOOLEAN,
    previouselapsedtime NUMERIC,
    previouseventdistancefromgoal NUMERIC,
    previouseventanglesigned NUMERIC,
    previouseventxnorm NUMERIC,
    previouseventynorm NUMERIC,
    timediff NUMERIC,
    isrebound BOOLEAN,
    isgoal BOOLEAN,
    xg NUMERIC,
    "time:elapsed game" TEXT,
    raw_data JSONB
);

-- 7. PLAYER_STATS: Mirror of aggregated metrics 
CREATE TABLE player_stats (
    id TEXT PRIMARY KEY,
    player1id BIGINT REFERENCES players(id),
    player1name TEXT,
    eventteam TEXT,
    strength TEXT,
    season BIGINT,
    seconds NUMERIC,
    minutes NUMERIC,
    goals NUMERIC,
    assists NUMERIC,
    points NUMERIC,
    shots NUMERIC,
    cf NUMERIC, ca NUMERIC,
    ff NUMERIC, fa NUMERIC,
    sf NUMERIC, sa NUMERIC,
    gf NUMERIC, ga NUMERIC,
    xg NUMERIC, xga NUMERIC,
    pf NUMERIC, pa NUMERIC,
    gamesplayed NUMERIC,
    scrapedon TEXT DEFAULT now()
);

-- 8. STANDINGS: Literal match of standings.csv [cite: 2]
CREATE TABLE standings (
    id TEXT PRIMARY KEY,
    conferenceabbrev TEXT,
    conferencehomesequence NUMERIC,
    conferencel10sequence NUMERIC,
    conferencename TEXT,
    conferenceroadsequence NUMERIC,
    conferencesequence NUMERIC,
    date DATE,
    divisionabbrev TEXT,
    divisionhomesequence NUMERIC,
    divisionl10sequence NUMERIC,
    divisionname TEXT,
    divisionroadsequence NUMERIC,
    divisionsequence NUMERIC,
    gametypeid BIGINT,
    gamesplayed NUMERIC,
    goaldifferential NUMERIC,
    goaldifferentialpctg NUMERIC,
    goalagainst NUMERIC,
    goalfor NUMERIC,
    goalsforpctg NUMERIC,
    homegamesplayed NUMERIC,
    homegoaldifferential NUMERIC,
    homegoalsagainst NUMERIC,
    homegoalsfor NUMERIC,
    homelosses NUMERIC,
    homeotlosses NUMERIC,
    homepoints NUMERIC,
    homeregulationplusotwins NUMERIC,
    homeregulationwins NUMERIC,
    hometies NUMERIC,
    homewins NUMERIC,
    l10gamesplayed NUMERIC,
    l10goaldifferential NUMERIC,
    l10goalsagainst NUMERIC,
    l10goalsfor NUMERIC,
    l10losses NUMERIC,
    l10otlosses NUMERIC,
    l10points NUMERIC,
    l10regulationplusotwins NUMERIC,
    l10regulationwins NUMERIC,
    l10ties NUMERIC,
    l10wins NUMERIC,
    leaguehomesequence NUMERIC,
    leaguel10sequence NUMERIC,
    leagueroadsequence NUMERIC,
    leaguesequence NUMERIC,
    losses NUMERIC,
    otlosses NUMERIC,
    pointpctg NUMERIC,
    points NUMERIC,
    regulationplusotwinpctg NUMERIC,
    regulationplusotwins NUMERIC,
    regulationwinpctg NUMERIC,
    regulationwins NUMERIC,
    roadgamesplayed NUMERIC,
    roadgoaldifferential NUMERIC,
    roadgoalsagainst NUMERIC,
    roadgoalsfor NUMERIC,
    roadlosses NUMERIC,
    roadotlosses NUMERIC,
    roadpoints NUMERIC,
    roadregulationplusotwins NUMERIC,
    roadregulationwins NUMERIC,
    roadties NUMERIC,
    roadwins NUMERIC,
    seasonid BIGINT,
    shootoutlosses NUMERIC,
    shootoutwins NUMERIC,
    streakcode TEXT,
    streakcount NUMERIC,
    teamlogo TEXT,
    ties NUMERIC,
    waiverssequence NUMERIC,
    wildcardsequence NUMERIC,
    winpctg NUMERIC,
    wins NUMERIC,
    scrapedon TEXT,
    source TEXT,
    placename_default TEXT,
    teamname_default TEXT,
    teamname_fr TEXT,
    teamcommonname_default TEXT,
    teamabbrev_default TEXT,
    placename_fr TEXT,
    teamcommonname_fr TEXT
);

-- 9. DRAFT: Literal match of draft.csv [cite: 1]
CREATE TABLE draft (
    id TEXT PRIMARY KEY,
    round NUMERIC,
    pickinround NUMERIC,
    overallpick NUMERIC,
    teamid BIGINT,
    teamabbrev TEXT,
    teamlogolight TEXT,
    teamlogodark TEXT,
    teampickhistory TEXT,
    positioncode TEXT,
    countrycode TEXT,
    height NUMERIC,
    weight NUMERIC,
    amateurleague TEXT,
    amateurclubname TEXT,
    year TEXT,
    scrapedon TEXT,
    source TEXT,
    teamname_default TEXT,
    teamname_fr TEXT,
    teamcommonname_default TEXT,
    teamplacenamewithpreposition_default TEXT,
    teamplacenamewithpreposition_fr TEXT,
    displayabbrev_default TEXT,
    firstname_default TEXT,
    lastname_default TEXT,
    firstname_cs TEXT,
    firstname_sk TEXT,
    lastname_cs TEXT,
    lastname_fi TEXT,
    lastname_sk TEXT,
    teamcommonname_fr TEXT
);