- name: Force Install and Run
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          PYTHON_EXE=$(which python3)
          $PYTHON_EXE -m pip install --upgrade pip
          $PYTHON_EXE -m pip install pandas sqlalchemy psycopg2-binary requests beautifulsoup4 lxml polars numpy selectolax xgboost joblib
          
          export PYTHONPATH=$GITHUB_WORKSPACE
          $PYTHON_EXE season_orchestrator.py